Backend Frameworks/Django-TvShows/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^homepage', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/episode', views.DetailEpisodeView.as_view(), name='detailEpisode'),
    url(r'^(?P<pk>[0-9]+)/profile', views.ProfileView.as_view(), name='profile'),
    url(r'^(?P<episode_id>[0-9]+)/markedWatched/$', views.markedWatched, name='markedWatched'),
    url(r'^register/$', views.register, name='register'),
    url(r'^addtvshow/$', views.TvShowsView.as_view(), name='tvshowregistration')
]

Backend Frameworks/Django-TvShows/tvshows/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from polls import views as core_views


urlpatterns = [
    url(r'^',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    url('accounts/', include('django.contrib.auth.urls')),
]

Backend Frameworks/Django-TvShows/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class TvShow(models.Model):
    nameTvShow = models.CharField('Show name', max_length=50)
    apparitionDate = models.DateField('Aired Date')
    endDate = models.DateField('Ended Date')
    episodeDuration = models.IntegerField('Duration Episode (minutes)', default=0)
    shortDescription = models.CharField('Short Description', max_length=200)
    genreTvShow = models.CharField('Genre', max_length=100)

    def __str__(self):
        return self.nameTvShow


class Series(models.Model):
    tvShow = models.ForeignKey(TvShow, on_delete=models.CASCADE)
    nameSeries = models.CharField('Series Name', max_length=100)
    numberSeries = models.IntegerField('Series Number', default=0)

    def __str__(self):
        return self.nameSeries


class Episode(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    episodeNumber = models.IntegerField('Episode Number', default=0)
    episodeName = models.CharField('Episode Name', max_length=100)
    episodeDescription = models.CharField('Episode Description', max_length=200)
    viewedEpisode = models.BooleanField('Watched', default=False)
    users = models.ManyToManyField('auth.User', through='EpisodeUser', related_name='episode')

    def __str__(self):
        return self.episodeName


class EpisodeUser(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.episode.episodeName + self.user.username

Backend Frameworks/Django-TvShows/polls/forms.py
from django import forms

from polls.models import TvShow


class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required=True,
        label='Username',
        max_length=32
    )
    email = forms.CharField(
        required=True,
        label='Email',
        max_length=32,
    )
    password = forms.CharField(
        required=True,
        label='Password',
        max_length=32,
        widget=forms.PasswordInput()
    )


class TvSeriesRegistrationForm(forms.ModelForm):
    """
    nameTvShow = forms.CharField(required=True, label='Tv Show Name: ', max_length=50)
    apparitionDate = forms.DateTimeField(required=True, label='Aired Date')
    endDate = forms.DateTimeField(required=True, label='Ended Date')
    episodeDuration = forms.IntegerField(required=True, label='Duration Episode (minutes)')
    shortDescription = forms.CharField(required=True, label='Short Description', max_length=200)
    genreTvShow = forms.CharField(required=True, label='Genre', max_length=100)
    """

    class Meta:
        model = TvShow
        fields = ['nameTvShow', 'apparitionDate', 'endDate', 'episodeDuration', 'shortDescription', 'genreTvShow']

Backend Frameworks/Django-TvShows/polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import forms, modelformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.generic import FormView

from polls import models
from polls.forms import UserRegistrationForm, TvSeriesRegistrationForm
from .models import TvShow, Episode, EpisodeUser
from django.contrib.auth import login, authenticate
from django.shortcuts import render


class IndexView(LoginRequiredMixin, generic.ListView):
        template_name = "polls/index.html"
        context_object_name = 'latestShowsList'

        def get_queryset(self):
            return TvShow.objects.all()


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = TvShow
    template_name = "polls/details.html"


class DetailEpisodeView(LoginRequiredMixin, generic.DetailView):
    model = Episode
    template_name = "polls/detailsEpisode.html"


class ProfileView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = "polls/profile.html"


class TvShowsView(FormView):
    template_name = 'polls/addTvShow.html'
    form_class = TvSeriesRegistrationForm
    success_url = '/homepage'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email = userObj['email']
            password = userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/homepage')
            else:
                raise forms.ValidationError('Looks like a username with that email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'polls/signup.html', {'form': form})


def markedWatched(request, episode_id):
    episode = get_object_or_404(Episode, pk=episode_id)
    binding = EpisodeUser(user=request.user, episode=episode)
    episodes = request.user.episode.all()
    ok = 0
    for epi in episodes:
        if epi == episode:
            messages.error(request, 'You already watched this episode')
            ok = 1
            break
    if ok == 0:
        binding.save()
    return HttpResponseRedirect(reverse('polls:detailEpisode', args=(episode.id,)))


#import pdb;
#pdb.set_trace()

Backend Frameworks/Django-TvShows/polls/templates/polls/addTvShow.html
{% extends 'polls/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

Backend Frameworks/Django-TvShows/polls/templates/polls/base.html
<head>
    <title>TvShows</title>
<style>
ul  {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    }

li  {
    float: left;
    }

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    }

li a:hover:not(.active) {
    background-color: #111;
    }

.active {
    background-color: #4CAF50;
    }
</style>
</head>

<body>
<ul>
    {% if user.is_authenticated %}
        <li><a href="{% url 'polls:index' %}">Home</a></li>
        <li><a href="{% url 'polls:profile' user.id%}"> Profile </a></li>
        <li><a href="{% url 'polls:tvshowregistration' %}"> AddTvShow </a></li>
        <li style="float:right"><a href="{% url 'logout'%}?next={{request.path}}">{{ user.get_username }} - Logout</a></li>
    {% else %}
        <li><a href="{% url 'polls:index' %}">Home</a></li>
        <li style="float:right"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
    {% endif %}
</ul>

{% if messages %}
    <div class="span12">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
    </div>
{% endif %}
{% block content %}{% endblock %}
</body>

Backend Frameworks/Django-TvShows/polls/templates/polls/details.html
{% include "polls/base.html" %}

<h1>{{ tvshow.nameTvShow }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load myapp_tags %}

{% for series in tvshow.series_set.all %}
    <h2>{{ series.nameSeries }}</h2>
        {% for episode in series.episode_set.all%}
            <h3><a href="{% url 'polls:detailEpisode' episode.id %}">{{ episode.episodeName }}</a></h3>
        {% endfor %}
{% endfor %}

Backend Frameworks/Django-TvShows/polls/templates/polls/detailsEpisode.html
{% include "polls/base.html" %}
{% load myapp_tags %}

<h1> {{ episode.episodeName }} </h1>
<p> Episode number: {{ episode.episodeNumber }} </p>
<p> Description {{ episode.episodeDescription }} </p>
<p> Did you watched it ?</p>
<form action="{% url 'polls:markedWatched' episode.id%}" method="post">
    {% csrf_token %}
    <button type="submit">Marked as watched</button>
</form>

Backend Frameworks/Django-TvShows/polls/templates/polls/index.html
{% include "polls/base.html" %}
{% load myapp_tags %}

<table>
    <tr>
        {% for show in latestShowsList %}
        <td>
            <h1><a href="{% url 'polls:detail' show.id %}">{{ show.nameTvShow }}</a></h1>
            <p>Apparition Date | {{ show.apparitionDate }} -> End Date | {{ show.endDate }} </p>
            <p>An episode {{ show.episodeDuration }} minutes</p>
            <p>Genre: {{ show.genreTvShow }} </p>
            <p>Short Description: {{ show.shortDescription }} </p>
        </td>
        {% if not forloop.counter|mod:2 %}
    </tr>
    <tr>
        {% endif %}
        {% endfor %}
    </tr>
</table>

Backend Frameworks/Django-TvShows/polls/templates/polls/profile.html
{% include "polls/base.html" %}

<h1>Welcome {{ user.username }}</h1>

<h2>You recently watched these episodes: </h2>

{% for episode in user.episode.all %}
    <h3><a href="{% url 'polls:detailEpisode' episode.id %}">{{ episode.episodeName }}</a></h3>
{% endfor %}

Backend Frameworks/Django-TvShows/polls/templates/polls/signup.html
{% extends 'polls/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
</head>
<body>

</body>
</html>

{% block content %}
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}